# Generated by Django 2.2.1 on 2019-05-24 15:37

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
